#include "decrypt.hpp"
#include "StringAnalysis.hpp"


int main(int argc, char** argv)
{
    //Caesar: "IT STY XYZRGQJ TAJW XTRJYMNSL GJMNSI DTZ"
    //Vigenere: "UPRCW IHSGY OXQJR IMXTW AXVEB DREGJ AFNIS EECAG SSBZR TVEZU RJCXT OGPCY OOACS EDBGF ZIFUB KVMZU FXCAD CAXGS FVNKM SGOCG FIOWN KSXTS ZNVIZ HUVME DSEZU LFMBL PIXWR MSPUS FJCCA IRMSR FINCZ CXSNI BXAHE LGXZC BESFG HLFIV ESYWO RPGBD SXUAR JUSAR GYWRS GSRZP MDNIH WAPRK HIDHU ZBKEQ NETEX ZGFUI FVRI"

    DecryptEngine dc_engine ("IT STY XYZRGQJ TAJW XTRJYMNSL GJMNSI DTZ");
    dc_engine.analyze_ciphertext();

    return 0;
}